[package]
name = "angle"
version = "0.2.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
flate2 = "1.0.35"
hematite-nbt = "0.5.2"
png = "0.17.14"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
uuid = { version = "1.11.0", features = ["rng", "v4"] }
